# Default values for node-normalization-loader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: "renciorg/cam-kp-api"
  tag: "0.1"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  host: ingress_HOST
  class: ingress_CLASS
  enabled: true

logs:
  storageSize: 3.5G

app:
  port: 8080
