apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "cam-kp-api.fullname" . }}-ingress-trapi-1-1
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: cam-kp-api-dev-tls-secret
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/1.1.0"
            backend:
              serviceName: {{ include "cam-kp-api.fullname" . }}-web-service-trapi-1-1
              servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "cam-kp-api.fullname" . }}-ingress-trapi-1-2
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: cam-kp-api-dev-tls-secret
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/1.2.0"
            backend:
              serviceName:  {{ include "cam-kp-api.fullname" . }}-web-service-trapi-1-2
              servicePort: 8081